# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - AltoroJ-3.2
pool: 
  name: default

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8' # 3.6,3.7,3.9
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
    
    
- script: pip install --extra-index-url https://test.pypi.org/simple/ boman-cli-uat==12.4 
  displayName: 'installing'

- script: |
    "C:\WINDOWS\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "C:\Users\Sathya\Downloads\vsts-agent-win-x64-3.238.0\for_work\_temp\9706b14b-272e-446a-9d08-23a254848bf2.cmd"" 
     boman-cli-uat -a run -u https://devapi.boman.ai/v2/"
  displayName: 'Running the scan'